import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import cn from "@/helper/cn";
import { ThemeWrapper } from "@/components";
import { Toaster } from "react-hot-toast";
import { JWTPayload } from "jose";

// const inter = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare module "next/server" {
  interface NextRequest {
    user?: JWTPayload;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("w-[100vw] h-[100vh] overflow-hidden")}>
        <Toaster position="top-center" />
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
